// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NullableSolutionFilter
{
    internal sealed partial class Vsix
    {
        public const string Id = "NullableSolutionFilter.b37a8d94-2fe4-4143-9f5f-e038d86642a1";
        public const string Name = "Nullable Solution Filter 64";
        public const string Description = @"Custom filter for Solution Explorer that excluded files and projects with nullable referenced type enabled. Useful while you convert your solution to have a NRT feature on.";
        public const string Language = "en-US";
        public const string Version = "0.1";
        public const string Author = "lsoft";
        public const string Tags = "nullable,NRE";
    }
}
